analysis:
  auto_approve_threshold: 95.0
  batch_size: 1000
  min_suggestions: 3
dashboard:
  auto_open: true
  create_html: true
  include_charts: true
email:
  generate_summary: false
  recipients: []
files:
  exceptions_file: source_CRPM_exceptions.xlsx
  input_file: source_CRPM_check.xlsx
  output_folder: output
hotels:
  city_tax_hotels:
  - AMS
  - AMA
  - AMZ
  - RTM
  - NYT
  - NYB
  - PGL
  - PCG
  - POP
  - PLD
  - GEN
  - ZUR
  - RIT
  - KLB
  excluded_hotels:
  - ITA
  - VRS
  - VRSM
